### ISSUE TITLE
FakeSMC sensors can't be injected,

### ISSUE THREAD

**Issue by roddy20** [khronokernel/Getting-Started-With-OpenCore#4]
FakeSMC sensors can be injected, exactly as any other kext
https://sourceforge.net/p/hwsensors/hwsensors3/code3/HEAD/tree/
I tried these with no problems
ACPIMonitor.kext
GeforceSensor.kext
IntelCPUMonitor.kext
W836x.kext
I hope any other will work too

**Comment by khronokernel** [comment]
> FakeSMC sensors can't be injected, alternative is HWSensors3 or VirtualSMC sensors.

It's specifically the stock FakeSMC sensors that aren't supported, I even list HWSensors3 as an alternative. Currently the stock sensors don't have official support but can still function on some systems but OpenCore may refuse to inject them randomly

**Comment by vit9696** [comment]
@khronokernel this makes no sense, to be honest. We are not aware of any issues with kext injection. If this is an issue, why would not you report it to our bugtracker? Also, include these "stock" kexts please, perhaps we are misunderstanding something :)

**Comment by khronokernel** [comment]
@vit9696 The specific kexts I'm referring to are the one's bundled with [Rehabman's FakeSMC](https://bitbucket.org/RehabMan/os-x-fakesmc-kozlek/downloads/)(calling them stock isn't good wording on my part). It was an issue seen on the InsanelyMac's discord and it was decided that the HWSensor's kexts didn't exhibit this issue. It was random on which kexts it chose not to load but this issue may have been quite small and already dealt with a fix for something else(or just user fault). This was back at the start of May I saw this so could be irrelevant at this point and since I didn't experience it myself the issue that's why I never reported it. I wanted to add it to the post as a heads up, I'll update accordingly if this isn't an issue. Apologies for any headaches my post may have caused
